'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import LeadKanban, { type KanbanLead, type LeadStage } from '../../../components/LeadKanban';
import Icon from '../../../components/Icon';

type Activity={type?:string;label?:string;detail?:string;at?:string};
type Lead=KanbanLead&{legalName?:string;address?:string;cnae?:string;cnaeDescription?:string;companySize?:string;legalNature?:string;capitalSocial?:number;taxSummary?:string;simples?:boolean|null;mei?:boolean|null;partners?:{name?:string;qualification?:string;joinedAt?:string}[];taxRegime?:{year?:number;form?:string;filings?:number}[];facebook?:string;googleMapsUrl?:string;qualification?:string;createdAt?:string;updatedAt?:string;owner?:string;externalSource?:string;externalId?:string;activity?:Activity[];anonymous?:boolean};
type Draft={name:string;company:string;email:string;phone:string;interest:string;source:string;status:string;estimatedValue:string;nextActionAt:string;owner:string;notes:string};
const PAGE_SIZE=15;
const EMPTY:Draft={name:'',company:'',email:'',phone:'',interest:'',source:'Cadastro manual',status:'novo',estimatedValue:'',nextActionAt:'',owner:'Arthur Ferreira',notes:''};
const STATUSES=['novo','qualificado','em_contato','proposta','negociacao','cliente','ativo','pausado','perdido'];
function currency(value?:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(value)||0)}
function normalizedStatus(value?:string){const status=(value||'novo').toLowerCase().trim().replaceAll(' ','_');if(status==='contato')return'em_contato';if(status==='convertido')return'cliente';return status}
function leadTitle(lead:Lead){return lead.company||lead.name||lead.email||'Lead sem nome'}
function statusLabel(value?:string){const status=normalizedStatus(value);return({novo:'Novo',qualificado:'Qualificado',em_contato:'Em contato',proposta:'Proposta',negociacao:'Negociação',cliente:'Convertido',ativo:'Cliente ativo',pausado:'Pausado',perdido:'Não converteu'} as Record<string,string>)[status]||status.replaceAll('_',' ')}
function localInputDate(value?:string|null){if(!value)return'';const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))return'';const offset=parsed.getTimezoneOffset()*60_000;return new Date(parsed.getTime()-offset).toISOString().slice(0,16)}
function formatActivityDate(value?:string){if(!value)return'';const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))return'';return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(parsed)}
function leadDraft(lead:Lead):Draft{return{name:lead.name||'',company:lead.company||'',email:lead.email||'',phone:lead.phone||'',interest:lead.interest||'',source:lead.source||'Cadastro manual',status:normalizedStatus(lead.status),estimatedValue:String(lead.estimatedValue||''),nextActionAt:localInputDate(lead.nextActionAt),owner:lead.owner||'Arthur Ferreira',notes:lead.notes||''}}

export default function AdminLeadsPage(){
  const[ready,setReady]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);const[leads,setLeads]=useState<Lead[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Lead|null>(null),[draft,setDraft]=useState<Draft>(EMPTY),[error,setError]=useState(''),[toast,setToast]=useState(''),[statusFilter,setStatusFilter]=useState('todos'),[page,setPage]=useState(1),[createOpen,setCreateOpen]=useState(false),[createDraft,setCreateDraft]=useState<Draft>(EMPTY);
  async function load(){setLoading(true);setError('');try{const session=await fetch('/api/admin/session',{cache:'no-store'});if(!session.ok){window.location.href='/admin/login';return}const response=await fetch('/api/leads',{cache:'no-store'});if(response.status===401){window.location.href='/admin/login';return}if(!response.ok)throw new Error('leads_unavailable');const data=await response.json() as {leads?:Lead[]};setLeads((Array.isArray(data.leads)?data.leads:[]).filter((lead)=>!lead.anonymous))}catch{setError('Não foi possível carregar o CRM agora.')}finally{setLoading(false);setReady(true)}}
  useEffect(()=>{void load()},[]);useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(''),2800);return()=>window.clearTimeout(timer)},[toast]);useEffect(()=>{document.body.style.overflow=selected||createOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[selected,createOpen]);
  const pipelineLeads=useMemo(()=>leads.filter((lead)=>STATUSES.includes(normalizedStatus(lead.status))),[leads]);
  const visible=useMemo(()=>{const text=query.trim().toLowerCase();return pipelineLeads.filter((lead)=>{const status=normalizedStatus(lead.status);const matches=statusFilter==='todos'||status===statusFilter;const haystack=[lead.name,lead.company,lead.email,lead.phone,lead.interest,lead.source,lead.cnpj,lead.website,lead.instagram,lead.owner,status].filter(Boolean).join(' ').toLowerCase();return matches&&(!text||haystack.includes(text))})},[pipelineLeads,query,statusFilter]);
  useEffect(()=>setPage(1),[query,statusFilter]);const totalPages=Math.max(1,Math.ceil(visible.length/PAGE_SIZE));const currentPage=Math.min(page,totalPages);const paged=visible.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);
  const converted=pipelineLeads.filter((lead)=>['cliente','ativo'].includes(normalizedStatus(lead.status))).length,lost=pipelineLeads.filter((lead)=>normalizedStatus(lead.status)==='perdido').length,open=pipelineLeads.filter((lead)=>!['cliente','ativo','perdido'].includes(normalizedStatus(lead.status))).length,totalValue=pipelineLeads.filter((lead)=>!['cliente','ativo','perdido'].includes(normalizedStatus(lead.status))).reduce((sum,lead)=>sum+(Number(lead.estimatedValue)||0),0),due=pipelineLeads.filter((lead)=>lead.nextActionAt&&new Date(lead.nextActionAt).getTime()<Date.now()&&!['cliente','ativo','perdido'].includes(normalizedStatus(lead.status))).length;
  function openLead(lead:Lead){setSelected(lead);setDraft(leadDraft(lead))}
  function moved(id:string,status:LeadStage){setLeads((current)=>current.map((lead)=>String(lead._id)===id?{...lead,status,updatedAt:new Date().toISOString(),activity:[...(lead.activity||[]),{type:'status_changed',label:`Movido para ${statusLabel(status)}`,at:new Date().toISOString()}]}:lead));setSelected((current)=>current&&String(current._id)===id?{...current,status}:current);setDraft((current)=>selected&&String(selected._id)===id?{...current,status}:current);setToast(status==='cliente'?'Lead marcado como convertido.':status==='perdido'?'Oportunidade marcada como não convertida.':'Etapa atualizada.')}
  async function saveSelected(event:FormEvent){event.preventDefault();if(!selected)return;setSaving(true);try{const response=await fetch('/api/leads',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:String(selected._id),...draft,estimatedValue:Number(draft.estimatedValue.replace(',','.'))||0,nextActionAt:draft.nextActionAt?new Date(draft.nextActionAt).toISOString():'',cnpj:selected.cnpj,address:selected.address,cnae:selected.cnae,cnaeDescription:selected.cnaeDescription,companySize:selected.companySize,capitalSocial:selected.capitalSocial,qualificationScore:selected.qualificationScore,externalSource:selected.externalSource,externalId:selected.externalId})});const data=await response.json() as {lead?:Lead;error?:string};if(!response.ok||!data.lead)throw new Error(data.error||'save_failed');setLeads((current)=>current.map((item)=>String(item._id)===String(data.lead!._id)?data.lead!:item));setSelected(data.lead);setDraft(leadDraft(data.lead));setToast('Lead atualizado no CRM.')}catch{setToast('Não foi possível salvar o lead.')}finally{setSaving(false)}}
  async function createLead(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...createDraft,estimatedValue:Number(createDraft.estimatedValue.replace(',','.'))||0,nextActionAt:createDraft.nextActionAt?new Date(createDraft.nextActionAt).toISOString():''})});const data=await response.json() as {lead?:Lead;error?:string};if(!response.ok||!data.lead)throw new Error(data.error||'create_failed');setLeads((current)=>[data.lead!,...current]);setCreateOpen(false);setCreateDraft(EMPTY);setToast('Lead criado no CRM.')}catch{setToast('Não foi possível criar o lead. Verifique duplicidade e dados.')}finally{setSaving(false)}}
  function pages(){const items=[];for(let value=Math.max(1,currentPage-2);value<=Math.min(totalPages,currentPage+2);value+=1)items.push(value);return items}
  if(!ready)return <main className="admin-loading"><div className="admin-loader"/><p>Organizando o CRM comercial</p></main>;

  return <main className="admin-radar-page admin-leads-page crm-v6-page"><div className="admin-radar-shell admin-leads-shell">
    <section className="admin-radar-title admin-leads-title"><div><span>THYNKXP / CRM COMERCIAL</span><h1>Gerenciar Leads</h1><p>Centralize prospecção, dados, responsáveis, próximas ações, valores, histórico e conversão em um único ecossistema.</p></div><div className="crm-v6-heading-actions"><button type="button" onClick={()=>{setCreateDraft(EMPTY);setCreateOpen(true)}}><Icon name="plus" size={14}/> Novo lead</button><a href="/admin/radar"><Icon name="search" size={14}/> Buscar novos leads</a></div></section>
    {error&&<div className="prospector-message is-error"><Icon name="shield"/><span>{error}</span><button type="button" onClick={()=>void load()}>Tentar novamente</button></div>}
    <section className="admin-lead-kpis crm-v6-kpis"><article><span>Em andamento</span><strong>{open}</strong><small>leads ativos no funil</small></article><article><span>Ações atrasadas</span><strong>{due}</strong><small>pedem atenção hoje</small></article><article><span>Convertidos</span><strong>{converted}</strong><small>viraram cliente</small></article><article><span>Não converteram</span><strong>{lost}</strong><small>oportunidades encerradas</small></article><article><span>Pipeline estimado</span><strong>{currency(totalValue)}</strong><small>valor das oportunidades abertas</small></article></section>

    <section className="lead-v5-list crm-v6-list"><div className="lead-v5-list-head"><div><span>BASE CENTRAL</span><h2>Leads, contatos e status</h2><p>{visible.length} registro{visible.length===1?'':'s'} no filtro · páginas de {PAGE_SIZE}.</p></div><label><Icon name="search" size={14}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar empresa, responsável, CNPJ, contato..."/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Limpar"><Icon name="x" size={11}/></button>}</label></div>
      <div className="admin-filter-tabs crm-v6-filters">{['todos',...STATUSES].map((status)=><button type="button" key={status} className={statusFilter===status?'is-active':''} onClick={()=>setStatusFilter(status)}>{status==='todos'?'Todos':statusLabel(status)}</button>)}</div>
      <div className="lead-v5-table-head crm-v6-table-head"><span>Lead</span><span>Status</span><span>Contato</span><span>Responsável</span><span>Próxima ação</span><span>Score</span></div>
      {paged.length?paged.map((lead)=><button className="lead-v5-row crm-v6-row" type="button" key={String(lead._id)} onClick={()=>openLead(lead)}><span><strong>{leadTitle(lead)}</strong><small>{lead.cnpj?`CNPJ ${lead.cnpj}`:lead.legalName||lead.interest||'Lead comercial'}</small></span><em data-status={normalizedStatus(lead.status)}>{statusLabel(lead.status)}</em><span><strong>{lead.phone||lead.email||'Sem contato direto'}</strong><small>{lead.email&&lead.phone?lead.email:lead.website||lead.instagram||'—'}</small></span><span><strong>{lead.owner||'Arthur Ferreira'}</strong><small>{lead.source||'Direto'}</small></span><span><strong>{lead.nextActionAt?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(lead.nextActionAt)):'Sem agenda'}</strong><small>{lead.nextActionAt&&new Date(lead.nextActionAt).getTime()<Date.now()?'Atrasada':'Próximo passo'}</small></span><span><strong>{Math.round(Number(lead.qualificationScore)||0)}/100</strong><small>{lead.qualification||'sem classificação'}</small></span></button>):<div className="admin-empty"><h3>Nenhum lead neste filtro</h3><p>Ajuste a busca, cadastre manualmente ou use o Radar.</p></div>}
      {visible.length>0&&<div className="crm-v6-pagination"><span>{(currentPage-1)*PAGE_SIZE+1}–{Math.min(currentPage*PAGE_SIZE,visible.length)} de {visible.length}</span><div><button disabled={currentPage===1} onClick={()=>setPage((value)=>Math.max(1,value-1))}>Anterior</button>{pages().map((value)=><button className={value===currentPage?'is-active':''} key={value} onClick={()=>setPage(value)}>{value}</button>)}<button disabled={currentPage===totalPages} onClick={()=>setPage((value)=>Math.min(totalPages,value+1))}>Próxima</button></div></div>}
    </section>

    <section className="admin-lead-kanban-shell crm-v6-kanban"><div className="admin-lead-kanban-toolbar"><div><span>QUADRO CRM</span><h2>Pipeline visual</h2><p>Arraste os cards; cada mudança fica registrada no histórico do lead.</p></div><span>{visible.length} lead{visible.length===1?'':'s'} no quadro</span></div><LeadKanban leads={visible} onOpen={(lead)=>openLead(lead as Lead)} onMoved={moved}/></section>
  </div>

  {selected&&<button className="lead-detail-backdrop" onClick={()=>setSelected(null)} aria-label="Fechar detalhes do lead"/>}
  <aside className={`lead-detail-drawer crm-v6-drawer ${selected?'is-open':''}`} aria-hidden={!selected}>{selected&&<><header><div><span>CRM / CONTROLE TOTAL</span><h2>{leadTitle(selected)}</h2><p>{selected.legalName&&selected.legalName!==leadTitle(selected)?selected.legalName:selected.interest||'Oportunidade comercial'}</p></div><button type="button" onClick={()=>setSelected(null)} aria-label="Fechar"><Icon name="x"/></button></header><div className="lead-detail-score"><span><small>Score comercial</small><strong>{Math.round(Number(selected.qualificationScore)||0)}<em>/100</em></strong></span><span><small>Etapa atual</small><strong>{statusLabel(selected.status)}</strong></span></div>
    <form className="crm-v6-editor" onSubmit={saveSelected}><h3>Controle comercial</h3><div className="crm-v6-grid"><label><span>Nome / contato</span><input value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></label><label><span>Empresa</span><input value={draft.company} onChange={(e)=>setDraft({...draft,company:e.target.value})}/></label><label><span>E-mail</span><input type="email" value={draft.email} onChange={(e)=>setDraft({...draft,email:e.target.value})}/></label><label><span>Telefone</span><input value={draft.phone} onChange={(e)=>setDraft({...draft,phone:e.target.value})}/></label><label><span>Etapa</span><select value={draft.status} onChange={(e)=>setDraft({...draft,status:e.target.value})}>{STATUSES.map((status)=><option value={status} key={status}>{statusLabel(status)}</option>)}</select></label><label><span>Responsável</span><input value={draft.owner} onChange={(e)=>setDraft({...draft,owner:e.target.value})}/></label><label><span>Valor estimado</span><input inputMode="decimal" value={draft.estimatedValue} onChange={(e)=>setDraft({...draft,estimatedValue:e.target.value})} placeholder="0,00"/></label><label><span>Próxima ação</span><input type="datetime-local" value={draft.nextActionAt} onChange={(e)=>setDraft({...draft,nextActionAt:e.target.value})}/></label><label className="is-wide"><span>Interesse / oportunidade</span><input value={draft.interest} onChange={(e)=>setDraft({...draft,interest:e.target.value})}/></label><label className="is-wide"><span>Observações comerciais</span><textarea value={draft.notes} onChange={(e)=>setDraft({...draft,notes:e.target.value})} rows={5}/></label></div><button className="crm-v6-save" disabled={saving}><Icon name="save" size={14}/>{saving?'Salvando...':'Salvar no CRM'}</button></form>
    <section className="lead-detail-section"><h3>Contato rápido</h3><div className="lead-detail-links">{selected.phone&&<a href={`https://wa.me/${selected.phone.replace(/\D/g,'').replace(/^(\d{10,11})$/,'55$1')}`} target="_blank" rel="noreferrer"><Icon name="whatsapp"/> WhatsApp</a>}{selected.email&&<a href={`mailto:${selected.email}`}><Icon name="mail"/> E-mail</a>}{selected.website&&<a href={selected.website} target="_blank" rel="noreferrer"><Icon name="globe"/> Site</a>}{selected.instagram&&<a href={selected.instagram} target="_blank" rel="noreferrer"><Icon name="instagram"/> Instagram</a>}{selected.googleMapsUrl&&<a href={selected.googleMapsUrl} target="_blank" rel="noreferrer"><Icon name="location"/> Maps</a>}</div></section>
    <section className="lead-detail-section"><h3>Empresa</h3><dl><div><dt>CNPJ</dt><dd>{selected.cnpj||'Não informado'}</dd></div><div><dt>CNAE</dt><dd>{selected.cnae?`${selected.cnae} · ${selected.cnaeDescription||''}`:'Não informado'}</dd></div><div><dt>Porte</dt><dd>{selected.companySize||'Não informado'}</dd></div><div><dt>Capital social</dt><dd>{selected.capitalSocial?currency(selected.capitalSocial):'Não informado'}</dd></div><div><dt>Tributação</dt><dd>{selected.taxSummary||'Não identificada'}</dd></div><div><dt>Natureza jurídica</dt><dd>{selected.legalNature||'Não informada'}</dd></div><div className="is-wide"><dt>Endereço</dt><dd>{selected.address||'Não informado'}</dd></div></dl></section>
    {Array.isArray(selected.partners)&&selected.partners.length>0&&<section className="lead-detail-section"><h3>Sócios públicos</h3><div className="lead-partner-list">{selected.partners.map((partner,index)=><div key={`${partner.name}-${index}`}><strong>{partner.name}</strong><span>{partner.qualification||'Qualificação não informada'}</span></div>)}</div></section>}
    <section className="lead-detail-section crm-v6-history"><h3>Histórico do lead</h3><div>{[...(selected.activity||[])].reverse().map((item,index)=><article key={`${item.at}-${index}`}><i/><span><strong>{item.label||'Atualização'}</strong>{item.detail&&<small>{item.detail}</small>}<time>{formatActivityDate(item.at)}</time></span></article>)}{!selected.activity?.length&&<p>As próximas movimentações deste lead aparecerão aqui.</p>}</div></section>
  </>}</aside>

  {createOpen&&<button className="lead-detail-backdrop is-create" onClick={()=>!saving&&setCreateOpen(false)} aria-label="Fechar novo lead"/>}{createOpen&&<div className="crm-v6-create-modal"><header><div><span>CRM / CADASTRO MANUAL</span><h2>Novo lead</h2><p>Cadastre uma oportunidade que não veio do Radar.</p></div><button type="button" onClick={()=>setCreateOpen(false)}><Icon name="x"/></button></header><form onSubmit={createLead}><div className="crm-v6-grid"><label><span>Nome do contato</span><input value={createDraft.name} onChange={(e)=>setCreateDraft({...createDraft,name:e.target.value})}/></label><label><span>Empresa</span><input value={createDraft.company} onChange={(e)=>setCreateDraft({...createDraft,company:e.target.value})}/></label><label><span>E-mail</span><input type="email" value={createDraft.email} onChange={(e)=>setCreateDraft({...createDraft,email:e.target.value})}/></label><label><span>Telefone</span><input value={createDraft.phone} onChange={(e)=>setCreateDraft({...createDraft,phone:e.target.value})}/></label><label><span>Interesse</span><input value={createDraft.interest} onChange={(e)=>setCreateDraft({...createDraft,interest:e.target.value})}/></label><label><span>Valor estimado</span><input value={createDraft.estimatedValue} onChange={(e)=>setCreateDraft({...createDraft,estimatedValue:e.target.value})}/></label><label><span>Responsável</span><input value={createDraft.owner} onChange={(e)=>setCreateDraft({...createDraft,owner:e.target.value})}/></label><label><span>Próxima ação</span><input type="datetime-local" value={createDraft.nextActionAt} onChange={(e)=>setCreateDraft({...createDraft,nextActionAt:e.target.value})}/></label><label className="is-wide"><span>Observações</span><textarea rows={4} value={createDraft.notes} onChange={(e)=>setCreateDraft({...createDraft,notes:e.target.value})}/></label></div><footer><button type="button" onClick={()=>setCreateOpen(false)}>Cancelar</button><button className="geo-primary" disabled={saving}><Icon name="plus" size={14}/>{saving?'Criando...':'Criar lead'}</button></footer></form></div>}
  {toast&&<div className="admin-toast lead-kanban-toast" role="status"><Icon name="check-circle"/> {toast}</div>}{loading&&<span className="admin-refreshing" aria-label="Atualizando"><i/></span>}
  </main>;
}
