'use client';

import { useEffect, useMemo, useState } from 'react';
import LeadKanban, { type KanbanLead, type LeadStage } from '../../../components/LeadKanban';
import Icon from '../../../components/Icon';

type Lead = KanbanLead & {
  legalName?: string; address?: string; cnae?: string; cnaeDescription?: string; companySize?: string; legalNature?: string; capitalSocial?: number;
  taxSummary?: string; simples?: boolean | null; mei?: boolean | null; partners?: { name?: string; qualification?: string; joinedAt?: string }[];
  taxRegime?: { year?: number; form?: string; filings?: number }[]; facebook?: string; googleMapsUrl?: string; qualification?: string; createdAt?: string; updatedAt?: string;
};

function currency(value?: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(Number(value) || 0); }
function normalizedStatus(value?: string) { const status=(value||'novo').toLowerCase().trim().replaceAll(' ','_'); if(status==='contato')return'em_contato'; if(status==='convertido')return'cliente'; return status; }
function leadTitle(lead: Lead) { return lead.company || lead.name || lead.email || 'Lead sem nome'; }
function statusLabel(value?: string) { const status=normalizedStatus(value); return ({novo:'Novo',qualificado:'Qualificado',em_contato:'Em contato',proposta:'Proposta',negociacao:'Negociação',cliente:'Convertido',ativo:'Cliente ativo',pausado:'Pausado',perdido:'Não converteu'} as Record<string,string>)[status] || status.replaceAll('_',' '); }

export default function AdminLeadsPage() {
  const [ready,setReady]=useState(false); const [loading,setLoading]=useState(false); const [leads,setLeads]=useState<Lead[]>([]); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Lead|null>(null); const [error,setError]=useState(''); const [toast,setToast]=useState(''); const [statusFilter,setStatusFilter]=useState('todos');

  async function load(){setLoading(true);setError('');try{const session=await fetch('/api/admin/session',{cache:'no-store'});if(!session.ok){window.location.href='/admin/login';return}const response=await fetch('/api/leads',{cache:'no-store'});if(response.status===401){window.location.href='/admin/login';return}if(!response.ok)throw new Error('leads_unavailable');const data=await response.json() as {leads?:Lead[]};setLeads((Array.isArray(data.leads)?data.leads:[]).filter((lead)=>!('anonymous'in lead)||!(lead as Lead&{anonymous?:boolean}).anonymous))}catch{setError('Não foi possível carregar o funil comercial agora.')}finally{setLoading(false);setReady(true)}}
  useEffect(()=>{void load()},[]);useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(''),2600);return()=>window.clearTimeout(timer)},[toast]);useEffect(()=>{document.body.style.overflow=selected?'hidden':'';return()=>{document.body.style.overflow=''}},[selected]);

  const pipelineLeads=useMemo(()=>leads.filter((lead)=>['novo','qualificado','em_contato','proposta','negociacao','cliente','ativo','pausado','perdido'].includes(normalizedStatus(lead.status))),[leads]);
  const visible=useMemo(()=>{const text=query.trim().toLowerCase();return pipelineLeads.filter((lead)=>{const status=normalizedStatus(lead.status);const matchesStatus=statusFilter==='todos'||status===statusFilter;const haystack=[lead.name,lead.company,lead.email,lead.phone,lead.interest,lead.source,lead.cnpj,lead.website,lead.instagram,status].filter(Boolean).join(' ').toLowerCase();return matchesStatus&&(!text||haystack.includes(text))})},[pipelineLeads,query,statusFilter]);
  const converted=pipelineLeads.filter((lead)=>['cliente','ativo'].includes(normalizedStatus(lead.status))).length; const lost=pipelineLeads.filter((lead)=>normalizedStatus(lead.status)==='perdido').length; const open=pipelineLeads.filter((lead)=>!['cliente','ativo','perdido'].includes(normalizedStatus(lead.status))).length; const totalValue=pipelineLeads.filter((lead)=>!['cliente','ativo','perdido'].includes(normalizedStatus(lead.status))).reduce((sum,lead)=>sum+(Number(lead.estimatedValue)||0),0);
  function moved(id:string,status:LeadStage){setLeads((current)=>current.map((lead)=>String(lead._id)===id?{...lead,status,updatedAt:new Date().toISOString()}:lead));setSelected((current)=>current&&String(current._id)===id?{...current,status}:current);setToast(status==='cliente'?'Lead marcado como convertido.':status==='perdido'?'Oportunidade marcada como não convertida.':'Etapa atualizada.')}

  if(!ready)return <main className="admin-loading"><div className="admin-loader"/><p>Organizando o funil comercial</p></main>;

  return <main className="admin-radar-page admin-leads-page">
    <div className="admin-radar-shell admin-leads-shell">
      <section className="admin-radar-title admin-leads-title"><div><span>THYNKXP / FUNIL COMERCIAL</span><h1>Leads</h1><p>Veja todos os leads, filtre por status e depois mova cada oportunidade no quadro até converter ou encerrar.</p></div><div className="admin-leads-header-actions"><a href="/admin/radar"><Icon name="search" size={14}/> Buscar novos leads</a></div></section>
      {error&&<div className="prospector-message is-error"><Icon name="shield"/><span>{error}</span><button type="button" onClick={()=>void load()}>Tentar novamente</button></div>}
      <section className="admin-lead-kpis"><article><span>Em andamento</span><strong>{open}</strong><small>leads ativos no funil</small></article><article><span>Convertidos</span><strong>{converted}</strong><small>viraram cliente</small></article><article><span>Não converteram</span><strong>{lost}</strong><small>oportunidades encerradas</small></article><article><span>Pipeline estimado</span><strong>{currency(totalValue)}</strong><small>valor das oportunidades abertas</small></article></section>

      <section className="lead-v5-list">
        <div className="lead-v5-list-head"><div><span>BASE DE LEADS</span><h2>Todos os leads e status atuais</h2><p>{visible.length} registro{visible.length===1?'':'s'} no filtro.</p></div><label><Icon name="search" size={14}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar empresa, contato, CNPJ..."/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Limpar"><Icon name="x" size={11}/></button>}</label></div>
        <div className="admin-filter-tabs">{['todos','novo','qualificado','em_contato','proposta','negociacao','cliente','perdido'].map((status)=><button type="button" key={status} className={statusFilter===status?'is-active':''} onClick={()=>setStatusFilter(status)}>{status==='todos'?'Todos':statusLabel(status)}</button>)}</div>
        <div className="lead-v5-table-head"><span>Lead</span><span>Status</span><span>Contato</span><span>Origem</span><span>Score</span></div>
        {visible.length?visible.slice(0,150).map((lead)=><button className="lead-v5-row" type="button" key={String(lead._id)} onClick={()=>setSelected(lead)}><span><strong>{leadTitle(lead)}</strong><small>{lead.cnpj?`CNPJ ${lead.cnpj}`:lead.legalName||lead.interest||'Lead comercial'}</small></span><em data-status={normalizedStatus(lead.status)}>{statusLabel(lead.status)}</em><span><strong>{lead.phone||lead.email||'Sem contato direto'}</strong><small>{lead.email&&lead.phone?lead.email:lead.website||lead.instagram||'—'}</small></span><span><strong>{lead.source||'Direto'}</strong><small>{lead.interest||'Interesse não definido'}</small></span><span><strong>{Math.round(Number(lead.qualificationScore)||0)}/100</strong><small>{lead.qualification||'sem classificação'}</small></span></button>):<div className="admin-empty"><h3>Nenhum lead neste filtro</h3><p>Ajuste a busca ou use o Radar para prospectar novas empresas.</p></div>}
      </section>

      <section className="admin-lead-kanban-shell"><div className="admin-lead-kanban-toolbar"><div><span>QUADRO</span><h2>Pipeline visual</h2><p>Arraste os cards para atualizar o status sem perder o contexto.</p></div><span>{visible.length} lead{visible.length===1?'':'s'} no quadro</span></div><LeadKanban leads={visible} onOpen={(lead)=>setSelected(lead as Lead)} onMoved={moved}/></section>
    </div>

    {selected&&<button className="lead-detail-backdrop" onClick={()=>setSelected(null)} aria-label="Fechar detalhes do lead"/>}
    <aside className={`lead-detail-drawer ${selected?'is-open':''}`} aria-hidden={!selected}>{selected&&<><header><div><span>INTELIGÊNCIA DO LEAD</span><h2>{leadTitle(selected)}</h2><p>{selected.legalName&&selected.legalName!==leadTitle(selected)?selected.legalName:selected.interest||'Oportunidade comercial'}</p></div><button type="button" onClick={()=>setSelected(null)} aria-label="Fechar"><Icon name="x"/></button></header><div className="lead-detail-score"><span><small>Score comercial</small><strong>{Math.round(Number(selected.qualificationScore)||0)}<em>/100</em></strong></span><span><small>Etapa atual</small><strong>{statusLabel(selected.status)}</strong></span></div><section className="lead-detail-section"><h3>Contato</h3><div className="lead-detail-links">{selected.phone&&<a href={`https://wa.me/${selected.phone.replace(/\D/g,'').replace(/^(\d{10,11})$/,'55$1')}`} target="_blank" rel="noreferrer"><Icon name="whatsapp"/> WhatsApp</a>}{selected.email&&<a href={`mailto:${selected.email}`}><Icon name="mail"/> E-mail</a>}{selected.website&&<a href={selected.website} target="_blank" rel="noreferrer"><Icon name="globe"/> Site</a>}{selected.instagram&&<a href={selected.instagram} target="_blank" rel="noreferrer"><Icon name="instagram"/> Instagram</a>}{selected.googleMapsUrl&&<a href={selected.googleMapsUrl} target="_blank" rel="noreferrer"><Icon name="location"/> Maps</a>}</div></section><section className="lead-detail-section"><h3>Empresa</h3><dl><div><dt>CNPJ</dt><dd>{selected.cnpj||'Não informado'}</dd></div><div><dt>CNAE</dt><dd>{selected.cnae?`${selected.cnae} · ${selected.cnaeDescription||''}`:'Não informado'}</dd></div><div><dt>Porte</dt><dd>{selected.companySize||'Não informado'}</dd></div><div><dt>Capital social</dt><dd>{selected.capitalSocial?currency(selected.capitalSocial):'Não informado'}</dd></div><div><dt>Tributação</dt><dd>{selected.taxSummary||'Não identificada'}</dd></div><div><dt>Natureza jurídica</dt><dd>{selected.legalNature||'Não informada'}</dd></div><div className="is-wide"><dt>Endereço</dt><dd>{selected.address||'Não informado'}</dd></div></dl></section>{Array.isArray(selected.partners)&&selected.partners.length>0&&<section className="lead-detail-section"><h3>Sócios públicos</h3><div className="lead-partner-list">{selected.partners.map((partner,index)=><div key={`${partner.name}-${index}`}><strong>{partner.name}</strong><span>{partner.qualification||'Qualificação não informada'}</span></div>)}</div></section>}{selected.notes&&<section className="lead-detail-section"><h3>Contexto comercial</h3><pre>{selected.notes}</pre></section>}</>}</aside>
    {toast&&<div className="admin-toast lead-kanban-toast" role="status"><Icon name="check-circle"/> {toast}</div>}{loading&&<span className="admin-refreshing" aria-label="Atualizando"><i/></span>}
  </main>;
}
