export type LeadNiche = { id: string; label: string; category: string; searchTerm: string; description: string; tags: string[]; popular?: boolean };

export const NICHE_CATEGORIES = ['Todos','Beleza & Bem-estar','Saúde','Alimentação','Fitness & Esporte','Pet','Serviços Profissionais','Casa & Construção','Automotivo','Varejo','Educação','Tecnologia & Marketing','Turismo & Eventos','Indústria & B2B'] as const;

export const NICHE_CATALOG: LeadNiche[] = [
  { id:'barbearia',label:'Barbearias',category:'Beleza & Bem-estar',searchTerm:'cabeleireiros',description:'Barbearias e serviços de corte masculino.',tags:['barbeiro','cabelo','masculino'],popular:true },
  { id:'salao-beleza',label:'Salões de beleza',category:'Beleza & Bem-estar',searchTerm:'cabeleireiros manicure e pedicure',description:'Salões, cabeleireiros e cuidados capilares.',tags:['salao','cabelo','beleza'],popular:true },
  { id:'estetica',label:'Clínicas de estética',category:'Beleza & Bem-estar',searchTerm:'atividades de estética e outros serviços de cuidados com a beleza',description:'Estética corporal, facial e cuidados de beleza.',tags:['estetica','beleza','spa'],popular:true },
  { id:'manicure',label:'Manicure & pedicure',category:'Beleza & Bem-estar',searchTerm:'manicure e pedicure',description:'Esmalterias e serviços de unhas.',tags:['unhas','esmalteria','pedicure'] },
  { id:'spa',label:'Spas & bem-estar',category:'Beleza & Bem-estar',searchTerm:'atividades de estética e cuidados com a beleza',description:'Spas, massagem e serviços de bem-estar.',tags:['spa','massagem','bem estar'] },
  { id:'clinica-medica',label:'Clínicas médicas',category:'Saúde',searchTerm:'atividade médica ambulatorial restrita a consultas',description:'Clínicas e consultórios médicos.',tags:['medico','clinica','consultorio'],popular:true },
  { id:'odontologia',label:'Clínicas odontológicas',category:'Saúde',searchTerm:'atividade odontológica',description:'Dentistas, clínicas e centros odontológicos.',tags:['dentista','odontologia','dental'],popular:true },
  { id:'fisioterapia',label:'Fisioterapia',category:'Saúde',searchTerm:'atividades de fisioterapia',description:'Clínicas e profissionais de fisioterapia.',tags:['fisio','reabilitacao'] },
  { id:'psicologia',label:'Psicologia',category:'Saúde',searchTerm:'atividades de psicologia e psicanálise',description:'Clínicas e consultórios de psicologia.',tags:['psicologo','terapia'] },
  { id:'nutricao',label:'Nutrição',category:'Saúde',searchTerm:'atividades de profissionais da nutrição',description:'Consultórios e clínicas de nutrição.',tags:['nutricionista','dieta'] },
  { id:'laboratorio',label:'Laboratórios clínicos',category:'Saúde',searchTerm:'laboratórios clínicos',description:'Análises clínicas e diagnóstico laboratorial.',tags:['exames','laboratorio'] },
  { id:'farmacia',label:'Farmácias & drogarias',category:'Saúde',searchTerm:'comércio varejista de produtos farmacêuticos',description:'Farmácias e drogarias.',tags:['farmacia','drogaria'] },
  { id:'restaurante',label:'Restaurantes',category:'Alimentação',searchTerm:'restaurantes e similares',description:'Restaurantes e operações gastronômicas.',tags:['comida','gastronomia'],popular:true },
  { id:'lanchonete',label:'Lanchonetes',category:'Alimentação',searchTerm:'lanchonetes casas de chá de sucos e similares',description:'Lanchonetes, casas de sucos e snacks.',tags:['lanche','suco'],popular:true },
  { id:'pizzaria',label:'Pizzarias',category:'Alimentação',searchTerm:'restaurantes e similares pizzaria',description:'Pizzarias e casas de massas.',tags:['pizza','delivery'] },
  { id:'padaria',label:'Padarias & confeitarias',category:'Alimentação',searchTerm:'padaria e confeitaria com predominância de revenda',description:'Padarias, confeitarias e panificação.',tags:['paes','confeitaria'],popular:true },
  { id:'cafeteria',label:'Cafeterias',category:'Alimentação',searchTerm:'lanchonetes casas de chá de sucos e similares cafeteria',description:'Cafés, cafeterias e casas de chá.',tags:['cafe','coffee'] },
  { id:'sorveteria',label:'Sorveterias',category:'Alimentação',searchTerm:'fabricação de sorvetes e outros gelados comestíveis',description:'Sorveterias e gelaterias.',tags:['sorvete','gelato'] },
  { id:'bar',label:'Bares & pubs',category:'Alimentação',searchTerm:'bares e outros estabelecimentos especializados em servir bebidas',description:'Bares, pubs e operações de bebidas.',tags:['bar','pub','bebidas'] },
  { id:'buffet-alimentos',label:'Buffets',category:'Alimentação',searchTerm:'serviços de alimentação para eventos e recepções buffet',description:'Buffets e alimentação para eventos.',tags:['buffet','eventos'] },
  { id:'academia',label:'Academias',category:'Fitness & Esporte',searchTerm:'atividades de condicionamento físico',description:'Academias, centros fitness e musculação.',tags:['fitness','musculacao','gym'],popular:true },
  { id:'pilates',label:'Pilates & funcional',category:'Fitness & Esporte',searchTerm:'atividades de condicionamento físico pilates',description:'Estúdios de pilates, funcional e treinamento.',tags:['pilates','funcional'] },
  { id:'escola-esportes',label:'Escolas de esportes',category:'Fitness & Esporte',searchTerm:'ensino de esportes',description:'Escolinhas, academias esportivas e treinamento.',tags:['futebol','natacao','esporte'] },
  { id:'petshop',label:'Pet shops',category:'Pet',searchTerm:'comércio varejista de animais vivos e artigos e alimentos para animais de estimação',description:'Pet shops, rações e acessórios.',tags:['pet','racao','animais'],popular:true },
  { id:'veterinaria',label:'Clínicas veterinárias',category:'Pet',searchTerm:'atividades veterinárias',description:'Clínicas, hospitais e consultórios veterinários.',tags:['veterinario','animais'] },
  { id:'banho-tosa',label:'Banho & tosa',category:'Pet',searchTerm:'higiene e embelezamento de animais domésticos',description:'Banho, tosa e estética animal.',tags:['banho','tosa','grooming'] },
  { id:'contabilidade',label:'Escritórios contábeis',category:'Serviços Profissionais',searchTerm:'atividades de contabilidade',description:'Contadores e escritórios de contabilidade.',tags:['contador','contabil'],popular:true },
  { id:'advocacia',label:'Escritórios de advocacia',category:'Serviços Profissionais',searchTerm:'serviços advocatícios',description:'Advogados e sociedades de advocacia.',tags:['advogado','juridico'],popular:true },
  { id:'arquitetura',label:'Escritórios de arquitetura',category:'Serviços Profissionais',searchTerm:'serviços de arquitetura',description:'Arquitetura, interiores e projetos.',tags:['arquiteto','projeto'] },
  { id:'engenharia',label:'Empresas de engenharia',category:'Serviços Profissionais',searchTerm:'serviços de engenharia',description:'Projetos, consultoria e engenharia.',tags:['engenheiro','projetos'] },
  { id:'imobiliaria',label:'Imobiliárias',category:'Serviços Profissionais',searchTerm:'corretagem na compra e venda e avaliação de imóveis',description:'Imobiliárias e corretoras de imóveis.',tags:['imovel','corretor'],popular:true },
  { id:'seguros',label:'Corretoras de seguros',category:'Serviços Profissionais',searchTerm:'corretores e agentes de seguros',description:'Corretoras e agentes de seguros.',tags:['seguro','corretora'] },
  { id:'rh',label:'RH & recrutamento',category:'Serviços Profissionais',searchTerm:'seleção e agenciamento de mão de obra',description:'Recrutamento, seleção e RH.',tags:['recrutamento','emprego'] },
  { id:'logistica',label:'Logística & transportes',category:'Serviços Profissionais',searchTerm:'transporte rodoviário de carga',description:'Transportadoras e operadores logísticos.',tags:['logistica','transportadora','frete'] },
  { id:'construtora',label:'Construtoras',category:'Casa & Construção',searchTerm:'construção de edifícios',description:'Construtoras e empresas de obras.',tags:['obra','construcao'],popular:true },
  { id:'eletrica',label:'Instalações elétricas',category:'Casa & Construção',searchTerm:'instalação e manutenção elétrica',description:'Empresas e prestadores de instalações elétricas.',tags:['eletricista','eletrica'] },
  { id:'hidraulica',label:'Instalações hidráulicas',category:'Casa & Construção',searchTerm:'instalações hidráulicas sanitárias e de gás',description:'Hidráulica, encanamento e instalações.',tags:['encanador','hidraulica'] },
  { id:'pintura',label:'Pintura & acabamento',category:'Casa & Construção',searchTerm:'serviços de pintura de edifícios em geral',description:'Pintura predial e acabamento.',tags:['pintor','acabamento'] },
  { id:'ar-condicionado',label:'Ar-condicionado',category:'Casa & Construção',searchTerm:'instalação e manutenção de sistemas centrais de ar condicionado',description:'Climatização, refrigeração e manutenção.',tags:['climatizacao','refrigeracao'] },
  { id:'energia-solar',label:'Energia solar',category:'Casa & Construção',searchTerm:'instalação e manutenção elétrica energia solar',description:'Instaladores e integradores de energia solar.',tags:['solar','fotovoltaica'] },
  { id:'marcenaria',label:'Marcenarias & móveis planejados',category:'Casa & Construção',searchTerm:'fabricação de móveis com predominância de madeira',description:'Marcenarias e móveis sob medida.',tags:['moveis','planejados','madeira'] },
  { id:'vidracaria',label:'Vidraçarias',category:'Casa & Construção',searchTerm:'comércio varejista de vidros',description:'Vidros, espelhos e instalações.',tags:['vidro','espelho'] },
  { id:'oficina',label:'Oficinas mecânicas',category:'Automotivo',searchTerm:'manutenção e reparação mecânica de veículos automotores',description:'Oficinas e reparação automotiva.',tags:['mecanica','carro'],popular:true },
  { id:'autopecas',label:'Autopeças',category:'Automotivo',searchTerm:'comércio a varejo de peças e acessórios novos para veículos automotores',description:'Lojas e distribuidores de autopeças.',tags:['pecas','carro'] },
  { id:'pneus',label:'Lojas de pneus',category:'Automotivo',searchTerm:'comércio a varejo de pneumáticos e câmaras de ar',description:'Pneus, rodas e serviços relacionados.',tags:['pneu','rodas'] },
  { id:'lavajato',label:'Lava-jatos & estética automotiva',category:'Automotivo',searchTerm:'serviços de lavagem lubrificação e polimento de veículos automotores',description:'Lavagem e estética automotiva.',tags:['lavagem','detailing'] },
  { id:'motos',label:'Oficinas de motos',category:'Automotivo',searchTerm:'manutenção e reparação de motocicletas e motonetas',description:'Oficinas e manutenção de motos.',tags:['moto','motocicleta'] },
  { id:'concessionaria',label:'Lojas de veículos',category:'Automotivo',searchTerm:'comércio a varejo de automóveis camionetas e utilitários usados',description:'Lojas, garagens e concessionárias.',tags:['veiculos','carros'] },
  { id:'roupas',label:'Lojas de roupas',category:'Varejo',searchTerm:'comércio varejista de artigos do vestuário e acessórios',description:'Moda, roupas e acessórios.',tags:['moda','vestuario'],popular:true },
  { id:'calcados',label:'Lojas de calçados',category:'Varejo',searchTerm:'comércio varejista de calçados',description:'Calçados e acessórios.',tags:['sapatos','calcados'] },
  { id:'cosmeticos',label:'Cosméticos & perfumaria',category:'Varejo',searchTerm:'comércio varejista de cosméticos produtos de perfumaria e de higiene pessoal',description:'Cosméticos, beleza e perfumaria.',tags:['cosmeticos','perfume'] },
  { id:'supermercado',label:'Supermercados & mercados',category:'Varejo',searchTerm:'comércio varejista de mercadorias em geral com predominância de produtos alimentícios supermercados',description:'Mercados, supermercados e minimercados.',tags:['mercado','supermercado'],popular:true },
  { id:'moveis',label:'Lojas de móveis',category:'Varejo',searchTerm:'comércio varejista de móveis',description:'Móveis residenciais e corporativos.',tags:['moveis','casa'] },
  { id:'eletronicos',label:'Eletrônicos & informática',category:'Varejo',searchTerm:'comércio varejista especializado de equipamentos e suprimentos de informática',description:'Informática, computadores e eletrônicos.',tags:['informatica','computador'] },
  { id:'joalheria',label:'Joalherias',category:'Varejo',searchTerm:'comércio varejista de artigos de joalheria',description:'Joias, relógios e acessórios.',tags:['joias','relogio'] },
  { id:'papelaria',label:'Papelarias',category:'Varejo',searchTerm:'comércio varejista de artigos de papelaria',description:'Papelaria, escritório e escolar.',tags:['papelaria','escolar'] },
  { id:'material-construcao',label:'Materiais de construção',category:'Varejo',searchTerm:'comércio varejista de materiais de construção em geral',description:'Lojas de materiais para obras e reformas.',tags:['construcao','obra'] },
  { id:'escola',label:'Escolas particulares',category:'Educação',searchTerm:'ensino fundamental',description:'Escolas privadas e instituições de ensino.',tags:['escola','colegio'],popular:true },
  { id:'idiomas',label:'Escolas de idiomas',category:'Educação',searchTerm:'ensino de idiomas',description:'Cursos de inglês e outros idiomas.',tags:['ingles','linguas'],popular:true },
  { id:'cursos',label:'Cursos profissionalizantes',category:'Educação',searchTerm:'outras atividades de ensino cursos',description:'Cursos livres e profissionalizantes.',tags:['curso','treinamento'] },
  { id:'creche',label:'Creches & educação infantil',category:'Educação',searchTerm:'educação infantil creche',description:'Creches e educação infantil.',tags:['creche','infantil'] },
  { id:'reforco',label:'Reforço escolar',category:'Educação',searchTerm:'atividades de apoio à educação',description:'Aulas de reforço e apoio educacional.',tags:['reforco','aulas'] },
  { id:'marketing',label:'Agências de marketing',category:'Tecnologia & Marketing',searchTerm:'agências de publicidade',description:'Marketing, publicidade e comunicação.',tags:['marketing','agencia','publicidade'],popular:true },
  { id:'software',label:'Software houses',category:'Tecnologia & Marketing',searchTerm:'desenvolvimento de programas de computador sob encomenda',description:'Desenvolvimento de software e sistemas.',tags:['software','sistemas','dev'],popular:true },
  { id:'ti',label:'Consultorias de TI',category:'Tecnologia & Marketing',searchTerm:'consultoria em tecnologia da informação',description:'Consultoria, suporte e serviços de TI.',tags:['ti','tecnologia','infra'] },
  { id:'design',label:'Design & branding',category:'Tecnologia & Marketing',searchTerm:'atividades de design',description:'Design gráfico, branding e identidade visual.',tags:['design','branding'] },
  { id:'fotografia',label:'Fotografia',category:'Tecnologia & Marketing',searchTerm:'atividades de produção de fotografias',description:'Fotógrafos e estúdios.',tags:['foto','fotografo'] },
  { id:'video',label:'Produtoras de vídeo',category:'Tecnologia & Marketing',searchTerm:'atividades de produção cinematográfica de vídeos',description:'Vídeo, audiovisual e produção de conteúdo.',tags:['video','produtora'] },
  { id:'grafica',label:'Gráficas',category:'Tecnologia & Marketing',searchTerm:'impressão de material para uso publicitário',description:'Gráficas, impressão e comunicação visual.',tags:['grafica','impressao'] },
  { id:'hotel',label:'Hotéis',category:'Turismo & Eventos',searchTerm:'hotéis',description:'Hotéis e meios de hospedagem.',tags:['hotel','hospedagem'],popular:true },
  { id:'pousada',label:'Pousadas',category:'Turismo & Eventos',searchTerm:'hotéis pousadas',description:'Pousadas e hospedagem independente.',tags:['pousada','hospedagem'] },
  { id:'viagens',label:'Agências de viagens',category:'Turismo & Eventos',searchTerm:'agências de viagens',description:'Turismo, viagens e pacotes.',tags:['turismo','viagem'] },
  { id:'eventos',label:'Espaços de eventos',category:'Turismo & Eventos',searchTerm:'serviços de organização de feiras congressos exposições e festas',description:'Casas de festas, eventos e cerimonial.',tags:['festa','evento'] },
  { id:'decoracao-eventos',label:'Decoração de eventos',category:'Turismo & Eventos',searchTerm:'serviços de organização de eventos decoração',description:'Decoração e produção de eventos.',tags:['decoracao','festas'] },
  { id:'metalurgica',label:'Metalúrgicas',category:'Indústria & B2B',searchTerm:'fabricação de estruturas metálicas',description:'Metalurgia, estruturas e fabricação metálica.',tags:['metal','industria'] },
  { id:'embalagens',label:'Embalagens',category:'Indústria & B2B',searchTerm:'fabricação de embalagens',description:'Fabricantes e fornecedores de embalagens.',tags:['embalagem','industria'] },
  { id:'confeccao',label:'Confecções',category:'Indústria & B2B',searchTerm:'confecção de peças do vestuário',description:'Confecções e indústria de vestuário.',tags:['confeccao','textil'] },
  { id:'alimentos-industria',label:'Indústria de alimentos',category:'Indústria & B2B',searchTerm:'fabricação de produtos alimentícios',description:'Fabricantes e processadores de alimentos.',tags:['alimentos','fabrica'] },
  { id:'distribuidora',label:'Distribuidoras & atacado',category:'Indústria & B2B',searchTerm:'comércio atacadista',description:'Distribuidores e operações atacadistas.',tags:['atacado','distribuidor'],popular:true },
];

export function normalizeNicheText(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(); }
